# Generated by Django 2.0.7 on 2018-07-04 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL),
        ),
    ]
