# Generated by Django 2.0.8 on 2018-10-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geem', '0002_auto_20180704_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='curation',
            field=models.CharField(choices=[('draft', 'draft'), ('review', 'under review'), ('release', 'released')], default='draft', max_length=7),
        ),
        migrations.AddField(
            model_name='package',
            name='ontology',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='root_name',
            field=models.CharField(default='new package', max_length=20),
        ),
        migrations.AddField(
            model_name='package',
            name='version',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
