# Generated by Django 2.0.8 on 2018-10-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geem', '0003_auto_20181015_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='root_name',
        ),
        migrations.AddField(
            model_name='package',
            name='file_base_name',
            field=models.CharField(default='new_resource', max_length=20),
        ),
        migrations.AddField(
            model_name='package',
            name='name',
            field=models.CharField(default='New Resource', max_length=40),
        ),
        migrations.AlterField(
            model_name='package',
            name='curation',
            field=models.CharField(choices=[('draft', 'draft'), ('review', 'under review'), ('release', 'release')], default='draft', max_length=7),
        ),
    ]
