# Generated by Django 2.0.8 on 2018-10-18 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geem', '0004_auto_20181018_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(default='New Resource', max_length=60),
        ),
    ]
