# Generated by Django 2.0.8 on 2018-10-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geem', '0005_auto_20181018_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='description',
            field=models.CharField(default='New resource description', max_length=255),
        ),
        migrations.AlterField(
            model_name='package',
            name='file_base_name',
            field=models.CharField(default='resource', max_length=20),
        ),
    ]
